### PR TITLE
Replace boto calls to use boto3

### PR DESCRIPTION
**Pull request by zcqian**
This partially addresses Issue #133 

All uses except for one usage has been replaced, and tested.

The explanation for the one remaining usage will be documented in comments under Issue #133

### CODE REVIEW

**Comment by zcqian** [comment]
Explanation of changes:
 - New functions `download_s3_file` and `get_s3_file_contents` have been created, names should be self explanatory.
 - The function `get_s3_file` is not removed. When `return_what="key"` the package `boto` is imported. I will make appropriate changes to this usage pattern in our organization so we don't depend on `boto`.
 - When `return_what` is `content` , `get_s3_file` is a wrapper for `get_s3_file_contents`. If `return_what` is not one of the two aforementioned values, `download_s3_file` is called.

Let me know what you think of the changes.

**Comment by zcqian** [comment]
Also, here's the code for testing the changes. Should have relatively high coverage for the changes in `biothings.utils.aws` https://gist.github.com/zcqian/7f9e498c0bac1e02a5f6b32c28f63ac2

**Comment by zcqian** [comment]
I think this is basically it, `boto` is no longer a required dependency except when the user calls `get_s3_file` and set the argument `return_what` to `"key"`. Calling the function will generate a `DeprecationWarning` , and setting that argument will either return the proper value or raise `ImportError` if `boto` is not installed.

I don't think any of our code uses `get_s3_file` any more.

**Comment by zcqian** [comment]
Let me know what else needs to be done before this can be merged.

Regarding the static code analysis, which reports 3 new issues in `biothings/utils/aws.py`:
1. The import outside top-level on line 124 is necessary to have `boto` as an optional dependency for those who depend on it. If we decide to remove the function (we won't use it anymore if we merge this patch) then this is not an issue. If not, then I think it's justified to do an import within the function -- should be obvious to anyone who uses that feature and run into issues. Later on we can remove the function. My plan is that we can gradually phase out dependency on `boto`: in 0.9.x we keep it as a dependency but only import when optional and warn users (which is what `get_s3_file` does in this patch). In the next version bump we remove the dependency, but leave the code as is so anyone other than us who use the functionality knows what to do (either install `boto` or update their code). Then finally we can remove that function. 
2. Too many arguments for `download_s3_file` on line 144. They recommend 5 arguments. If we want to maintain the convention, we will have 4 arguments related to s3 (key, bucket, id, secret). We need at least the local path so that makes it 5. However, even though all current usages overwrites the existing file (seems to previous behavior), I would still like to keep the default as not overwriting, and give anyone who uses this function the choice, hence one more necessary argument.
3. Unnecessary "else" after "return" (no-else-return) on line 224: it was already there before I changed anything, and I think it looks more obvious (Python implicitly returns `None`, that redundant code just makes it explicit)

**Comment by namespacestd0** [comment]
Following our conversation, we established it's helpful to perform integration test so that we know this commit does not introduce side effects, consider where redirection is used and how it affects this commit, and resolve certain codacy comments. In conclusion, I am not in a place to merge this branch immediately because the lack of certain information. However, the overall approach is very good and I advise to proceed with the author @zcqian 's best judgement. Please feel free to merge it when you see fit, probably after testing that it works with a running hub. cc @newgene

**Comment by zcqian** [comment]
Explanation regarding the redirects:

We are setting redirects on some S3 objects but the redirects only function when accessed over the static website -- which needs to be explicitly enabled but we don't seem to be using it.

A new function `get_s3_static_website_url` is introduced to facilitate testing of the 301 redirects. Previously the website feature was also implemented in https://github.com/biothings/biothings.api/blob/621887f04aae13c3a775aea9aa7daacb92ae7ef0/biothings/utils/aws.py#L185-L193

**Comment by zcqian** [comment]
Closing for potential merge issues (I don't get how git works)

**Pull request closed without merging**
