### PR TITLE
Add the dataplugin template subdirectory to the MANIFEST ...

### PR DESCRIPTION
**Pull request by ctrl-schaff**
Due to the templates directory containing non python files and the directory also not including an __init__.py, it wouldn't be automatically discovered during the installation process and would not copy the file to the site packages

This causes an exception when attempting to run the following command: biothings-cli dataplugin create

The command line tooling expects to find a manifest template at that location in the site-packages

### CODE REVIEW

**Comment by ctrl-schaff** [comment]
https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html

**Comment by newgene** [comment]
@ctrl-schaff this would be a reasonable fix. But I noticed we have this line in `setup.py` file:

https://github.com/biothings/biothings.api/blob/8736c4c8cdc3c66750e10ec04b3c6fed1dfea209/setup.py#L139

when I was wondering why those `*.tpl` files directly under `hub/dataplugin` folder were already included, but `manifest.yaml.tpl` is not.

Given this line we already have, and `MANIFEST.in` file is likely deprecated soon, I think we can modify the line to include `*.tpl` (v.s. `*.py.tpl`). Thoughts?

**Comment by ctrl-schaff** [comment]
> @ctrl-schaff this would be a reasonable fix. But I noticed we have this line in `setup.py` file:
> 
> https://github.com/biothings/biothings.api/blob/8736c4c8cdc3c66750e10ec04b3c6fed1dfea209/setup.py#L139
> 
> when I was wondering why those `*.tpl` files directly under `hub/dataplugin` folder were already included, but `manifest.yaml.tpl` is not.
> 
> Given this line we already have, and `MANIFEST.in` file is likely deprecated soon, I think we can modify the line to include `*.tpl` (v.s. `*.py.tpl`). Thoughts?

I just verified that the modification worked for me locally. I've used both `package_data` and `MANIFEST` based file distribution before so I don't mind either way. I am curious about the `MANIFEST.in` deprecation I hadn't heard about that, and I do think that it is a little odd to have two different ways of adding the files. If we're currently using the `setup.py` way I think we should probably continue using that

**Comment by newgene** [comment]
yeah, not sure about its "official" deprecation, just we likely to move to use `pyproject.toml` at some point and deprecate `setup.py`, `MANIFEST.in` all together. When this happens, we don't need any other module-level setup files. Everything should be included in `pyproject.toml` (For example, our `biothings_client` package has already moved to `pyproject.toml`).

**Comment by newgene** [comment]
@ctrl-schaff 👍 the only thing left is to change this PR to merge into `0.12.x` branch, our current dev branch, instead of `master`.

**Pull request merged**
